### ISSUE TITLE
Battery Management (red indicator)

### ISSUE THREAD

**Issue by anasAlsalol** [KirillSerogodsky/HP-ProBook-430-440-450-G6-Hackintosh#2]
![Screen Shot 2020-08-29 at 8 42 21 AM](https://user-images.githubusercontent.com/3209242/91629705-f8d06680-e9d3-11ea-870f-053ae4be6796.png)
![Screen Shot 2020-08-29 at 8 44 41 AM](https://user-images.githubusercontent.com/3209242/91629707-fa9a2a00-e9d3-11ea-99b1-13c40ff9fc1a.png)

**Comment by anasAlsalol** [comment]
after upgrade to macOS Big Sur 11.0  , issue resolved .

**Comment by whenmusicattacks** [comment]
is there any way to fix on Catalina?

**Comment by mehmetyukcell** [comment]
> is there any way to fix on Catalina?

[BATT.zip](https://github.com/KirillSerogodsky/HP-ProBook-430-440-450-G6-Hackintosh/files/5744814/BATT.zip)

Please, should be tried using ACPI file and patch with OpenCore.

**Comment by whenmusicattacks** [comment]
i was not able to get te OC version working, just Clover one :(

**Comment by TzeKitKwok** [comment]
> > is there any way to fix on Catalina?
> 
> [BATT.zip](https://github.com/KirillSerogodsky/HP-ProBook-430-440-450-G6-Hackintosh/files/5744814/BATT.zip)
> 
> Please, should be tried using ACPI file and patch with OpenCore.

After a period of restarting the computer there is a self-test error, enter macOS battery status shows recommended repair, can you help me look at it?
![IMG_0883(20210210-103522)](https://user-images.githubusercontent.com/42382226/107478007-b8e0f280-6bb3-11eb-9c85-c7d65fb9802a.JPG)

**Comment by TzeKitKwok** [comment]
> > is there any way to fix on Catalina?
> 
> [BATT.zip](https://github.com/KirillSerogodsky/HP-ProBook-430-440-450-G6-Hackintosh/files/5744814/BATT.zip)
> 
> Please, should be tried using ACPI file and patch with OpenCore.

Hi, your battery patch applies to my HP Zhan 66 Pro G1 , can this battery patch be uploaded to my GitHub repository? Easy to use and reference for everyone?
