### ISSUE TITLE
Battery status won't work and trackpad is out of function

### ISSUE THREAD

**Issue by tardar** [KirillSerogodsky/HP-ProBook-430-440-450-G6-Hackintosh#3]
Hey together,

i adapted your config into mine but now the battery status and the trackpad won't work.

Can you help me to get this working?

I uploaded my refi here for you.
Thanks for helping - you did a very great job 👍 

PS: I think that has to do with my DSDT patch - I don't know how that works so please help if you have the time for ;)
[EFI.zip](https://github.com/KirillSerogodsky/HP-ProBook-430-440-450-G6-Hackintosh/files/5152082/EFI.zip)

Hearthly Greetings
Tardar

**Comment by KirillSerogodsky** [comment]
Let's try this. You don't add SMBIOS info.
[config.plist.zip](https://github.com/KirillSerogodsky/HP-ProBook-430-440-450-G6-Hackintosh/files/5152339/config.plist.zip)

**Comment by tardar** [comment]
i removed that for uploading here.
In my system a SMBIOS is existing :)
